server:
  port: 8083

spring:
  application:
    name: course-service

  datasource:
    url: jdbc:postgresql://localhost:5432/coursedb
    username: postgres
    password: Shareef@1234
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # =========================
  # 🔥 REDIS CACHE
  # =========================
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  # =========================
  # 🔥 KAFKA CONFIG (JSON MODE - MATCH VIDEO SERVICE)
  # =========================
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: course-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: java.util.HashMap
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

# =========================
# 🔐 JWT (MUST MATCH AUTH SERVICE)
# =========================
jwt:
  secret: mysupersecretkeymysupersecretkey
  expiration: 3600000

# =========================
# 🔥 TOPICS
# =========================
topics:
  batch-assignment: batch-assignment
  batch-lifecycle: batch-lifecycle
  course: course-events
  content: content-events