server:
  port: 8084

spring:
  application:
    name: video-service

  datasource:
    url: jdbc:postgresql://localhost:5432/videodb
    username: postgres
    password: Shareef@1234
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  # =========================
  # 🔥 KAFKA CONFIG (FINAL WORKING JSON MODE)
  # =========================
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: video-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: java.util.HashMap
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

video:
  upload-dir: videos

jwt:
  secret: mysupersecretkeymysupersecretkey
  expiration: 3600000

topics:
  video: video-uploaded
  batch-assignment: batch-assignment
  batch-lifecycle: batch-lifecycle
