package com.lms.attendance.service;

import com.lms.attendance.entity.Attendance;
import com.lms.attendance.entity.AttendanceStatus;
import com.lms.attendance.entity.TrainerSessionAttendance;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.WeekFields;
import java.util.List;
import java.util.Locale;

// NEW — builds .xlsx reports strictly from existing entity fields (Attendance / TrainerSessionAttendance).
// Day / Week Number / Month / Year are display breakdowns of the existing date field, not new stored data.
// "Generated By" / "Generated Date" are report metadata (who ran the export and when), not attendance data.
@Service
public class ExcelReportService {

    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("dd-MM-yyyy");
    private static final DateTimeFormatter DATETIME_FMT = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    // =======================================================
    // STUDENT ATTENDANCE REPORT (from Attendance entity rows)
    // =======================================================
    public byte[] generateAttendanceExcel(List<Attendance> rows, String generatedBy) {
        try (Workbook wb = new XSSFWorkbook(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            Sheet sheet = wb.createSheet("Attendance Report");
            CellStyle headerStyle = headerStyle(wb);

            String[] headers = {
                    "Batch ID", "Student Email", "Trainer Email", "Attendance Date",
                    "Day", "Status", "Week Number", "Month", "Year",
                    "Organization ID", "Created At"
            };
            writeHeaderRow(sheet, headers, headerStyle);

            int rowIdx = 1;
            int present = 0, absent = 0, late = 0;

            for (Attendance a : rows) {
                Row row = sheet.createRow(rowIdx++);
                LocalDate date = a.getAttendanceDate();

                row.createCell(0).setCellValue(a.getBatchId() != null ? a.getBatchId() : 0);
                row.createCell(1).setCellValue(nullSafe(a.getStudentEmail()));
                row.createCell(2).setCellValue(nullSafe(a.getTrainerEmail()));
                row.createCell(3).setCellValue(date != null ? date.format(DATE_FMT) : "");
                row.createCell(4).setCellValue(date != null ? date.getDayOfWeek().toString() : "");
                row.createCell(5).setCellValue(a.getStatus() != null ? a.getStatus().name() : "");
                row.createCell(6).setCellValue(date != null ? weekNumber(date) : 0);
                row.createCell(7).setCellValue(date != null ? date.getMonth().toString() : "");
                row.createCell(8).setCellValue(date != null ? date.getYear() : 0);
                row.createCell(9).setCellValue(nullSafe(a.getOrganizationId()));
                row.createCell(10).setCellValue(a.getCreatedAt() != null ? a.getCreatedAt().format(DATETIME_FMT) : "");

                if (a.getStatus() == AttendanceStatus.PRESENT) present++;
                else if (a.getStatus() == AttendanceStatus.ABSENT) absent++;
                else if (a.getStatus() == AttendanceStatus.LATE) late++;
            }

            writeSummary(wb, sheet, rowIdx, rows.size(), present, absent, late, generatedBy);

            for (int i = 0; i < headers.length; i++) {
                sheet.autoSizeColumn(i);
            }

            wb.write(out);
            return out.toByteArray();

        } catch (IOException e) {
            throw new UncheckedIOException("Failed to generate attendance Excel report", e);
        }
    }

    // =======================================================
    // TRAINER SESSION ATTENDANCE REPORT (from TrainerSessionAttendance entity rows)
    // =======================================================
    public byte[] generateSessionExcel(List<TrainerSessionAttendance> rows, String generatedBy) {
        try (Workbook wb = new XSSFWorkbook(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            Sheet sheet = wb.createSheet("Trainer Session Report");
            CellStyle headerStyle = headerStyle(wb);

            String[] headers = {
                    "Batch ID", "Trainer Email", "Session Date", "Day", "Status",
                    "Week Number", "Month", "Year", "Organization ID", "Marked At"
            };
            writeHeaderRow(sheet, headers, headerStyle);

            int rowIdx = 1;
            int present = 0, absent = 0, late = 0;

            for (TrainerSessionAttendance s : rows) {
                Row row = sheet.createRow(rowIdx++);
                LocalDate date = s.getSessionDate();

                row.createCell(0).setCellValue(s.getBatchId() != null ? s.getBatchId() : 0);
                row.createCell(1).setCellValue(nullSafe(s.getTrainerEmail()));
                row.createCell(2).setCellValue(date != null ? date.format(DATE_FMT) : "");
                row.createCell(3).setCellValue(date != null ? date.getDayOfWeek().toString() : "");
                row.createCell(4).setCellValue(s.getStatus() != null ? s.getStatus().name() : "");
                row.createCell(5).setCellValue(date != null ? weekNumber(date) : 0);
                row.createCell(6).setCellValue(date != null ? date.getMonth().toString() : "");
                row.createCell(7).setCellValue(date != null ? date.getYear() : 0);
                row.createCell(8).setCellValue(nullSafe(s.getOrganizationId()));
                row.createCell(9).setCellValue(s.getMarkedAt() != null ? s.getMarkedAt().format(DATETIME_FMT) : "");

                if (s.getStatus() == AttendanceStatus.PRESENT) present++;
                else if (s.getStatus() == AttendanceStatus.ABSENT) absent++;
                else if (s.getStatus() == AttendanceStatus.LATE) late++;
            }

            writeSummary(wb, sheet, rowIdx, rows.size(), present, absent, late, generatedBy);

            for (int i = 0; i < headers.length; i++) {
                sheet.autoSizeColumn(i);
            }

            wb.write(out);
            return out.toByteArray();

        } catch (IOException e) {
            throw new UncheckedIOException("Failed to generate trainer session Excel report", e);
        }
    }

    // ---- shared helpers ----

    private void writeHeaderRow(Sheet sheet, String[] headers, CellStyle headerStyle) {
        Row headerRow = sheet.createRow(0);
        for (int i = 0; i < headers.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }
    }

    private void writeSummary(Workbook wb, Sheet sheet, int startRow, int total,
                               int present, int absent, int late, String generatedBy) {
        CellStyle labelStyle = wb.createCellStyle();
        Font boldFont = wb.createFont();
        boldFont.setBold(true);
        labelStyle.setFont(boldFont);

        double pct = total > 0 ? ((present + late) * 100.0 / total) : 0.0;

        int r = startRow + 1;
        r = writeSummaryLine(sheet, r, "Total Sessions", String.valueOf(total), labelStyle);
        r = writeSummaryLine(sheet, r, "Present Count", String.valueOf(present), labelStyle);
        r = writeSummaryLine(sheet, r, "Absent Count", String.valueOf(absent), labelStyle);
        r = writeSummaryLine(sheet, r, "Late Count", String.valueOf(late), labelStyle);
        r = writeSummaryLine(sheet, r, "Attendance Percentage", String.format(Locale.US, "%.1f%%", pct), labelStyle);
        r = writeSummaryLine(sheet, r, "Generated By", nullSafe(generatedBy), labelStyle);
        writeSummaryLine(sheet, r, "Generated Date", LocalDateTime.now().format(DATETIME_FMT), labelStyle);
    }

    private int writeSummaryLine(Sheet sheet, int rowIdx, String label, String value, CellStyle labelStyle) {
        Row row = sheet.createRow(rowIdx);
        Cell labelCell = row.createCell(0);
        labelCell.setCellValue(label);
        labelCell.setCellStyle(labelStyle);
        row.createCell(1).setCellValue(value);
        return rowIdx + 1;
    }

    private CellStyle headerStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setBold(true);
        font.setColor(IndexedColors.WHITE.getIndex());
        style.setFont(font);
        style.setFillForegroundColor(IndexedColors.DARK_TEAL.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        return style;
    }

    private int weekNumber(LocalDate date) {
        return date.get(WeekFields.of(Locale.getDefault()).weekOfWeekBasedYear());
    }

    private String nullSafe(String s) {
        return s == null ? "" : s;
    }
}