name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        service:
          - api-gateway
          - auth-service
          - user-service
          - course-service
          - video-service
          - notification-service
          - analytics-service
          - assessment
          - enrollment-service
          - progress-service
          - search-service
          - payment-service
          - file-service
          - student-service
          - attendance-service
          - batch-service
          - chat-service

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: |
          SERVICE=${{ matrix.service }}
          docker build -t shareef123/$SERVICE:latest ./$SERVICE

      - name: Push Image
        run: |
          SERVICE=${{ matrix.service }}
          docker push shareef123/$SERVICE:latest


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd TexoraAI.skills-server
            git pull origin main
            docker compose pull
            docker compose up -d --remove-orphans